@url = http://localhost:5002
@customerId = 00000000-0000-0000-0000-000000000000
@state = valid

###
GET {{url}}/customers

###
GET {{url}}/customers/{{customerId}}

###
GET {{url}}/customers/{{customerId}}/state

###
POST {{url}}/customers
Content-Type: application/json

{
  "customerId": "{{customerId}}",
  "fullname": "John Doe",
  "address": "New York City, Street XYZ"
}

###
PUT {{url}}/customers/{{customerId}}/state/{{state}}
Content-Type: application/json

{
  "customerId": "{{customerId}}",
  "state": "{{state}}"
}