@url = http://localhost:5002
@customerId = 8b5bcbc8-b18a-41ef-9f4e-c80e293af0aa

###
GET {{url}}/customers

###
GET {{url}}/customers/{{customerId}}

###
POST {{url}}/customers

{
  "id": "{{customerId}}",
  "fullname": "John Doe",
  "address": "New York City, Street XYZ"
}